sudo: required

language: javascript

services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"
  - echo C?7M?p-Gg^.9#h_ | docker login -u gisthive --password-stdin
  - echo "Docker Hub credentials are working"

script:
  - docker ps -a

after_success:
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
- docker build -t udagram-frontend ./udagram-frontend
- docker tag udagram-api-feed gisthive/udagram-api-feed:latest
- docker tag udagram-api-user gisthive/udagram-api-user:latest
- docker tag udagram-reverseproxy gisthive/udagram-reverseproxy:latest
- docker tag udagram-frontend gisthive/udagram-frontend:latest
- docker push gisthive/udagram-api-user:latest
- docker push gisthive/udagram-api-feed:latest
- docker push gisthive/udagram-reverseproxy:latest
- docker push gisthive/udagram-frontend:latest